services:
  server:
    image: domicile_mirror_server:latest
    restart: always
    ports:
      - "7775:7775/udp"
      - "7776:7776/tcp"
    volumes:
      - /etc/letsencrypt/live/domicile.tobiasbohn.com/cert.pfx:/domicile/cert.pfx
